[package]
name = "mex_be"
version = "0.1.0"
authors = ["skariel"]

[dependencies]
clippy = "*"
websocket = {version = "*", features = ["nightly"]}
parking_lot = {version = "*", features = ["nightly"]}